// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFirstPhoto(arg1) {
  return window['go']['main']['App']['CopyFirstPhoto'](arg1);
}

export function GetDeviceDetail(arg1) {
  return window['go']['main']['App']['GetDeviceDetail'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ScanDCIM(arg1) {
  return window['go']['main']['App']['ScanDCIM'](arg1);
}
