// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';

export function GetDeviceDetail(arg1:string):Promise<device.DeviceDetail>;

export function ListDevices():Promise<Array<device.DeviceInfo>>;

export function ScanDCIM(arg1:string):Promise<Array<device.PhotoFile>>;
