// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBackup() {
  return window['go']['main']['App']['CancelBackup']();
}

export function CheckAppleDevicesInstalled() {
  return window['go']['main']['App']['CheckAppleDevicesInstalled']();
}

export function CheckBackupPath(arg1) {
  return window['go']['main']['App']['CheckBackupPath'](arg1);
}

export function CheckTrustStatus(arg1) {
  return window['go']['main']['App']['CheckTrustStatus'](arg1);
}

export function EstimateBackupSize(arg1, arg2) {
  return window['go']['main']['App']['EstimateBackupSize'](arg1, arg2);
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetBackupEstimate(arg1, arg2) {
  return window['go']['main']['App']['GetBackupEstimate'](arg1, arg2);
}

export function GetBackupFolderSize(arg1) {
  return window['go']['main']['App']['GetBackupFolderSize'](arg1);
}

export function GetBackupHistory() {
  return window['go']['main']['App']['GetBackupHistory']();
}

export function GetConnectedDevice() {
  return window['go']['main']['App']['GetConnectedDevice']();
}

export function GetDefaultBackupPath() {
  return window['go']['main']['App']['GetDefaultBackupPath']();
}

export function GetDeviceDetail(arg1) {
  return window['go']['main']['App']['GetDeviceDetail'](arg1);
}

export function GetDiskInfo(arg1) {
  return window['go']['main']['App']['GetDiskInfo'](arg1);
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function InstallAppleDevices() {
  return window['go']['main']['App']['InstallAppleDevices']();
}

export function InstallHeicCodec() {
  return window['go']['main']['App']['InstallHeicCodec']();
}

export function LaunchAppleDevices() {
  return window['go']['main']['App']['LaunchAppleDevices']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ManifestExists(arg1, arg2) {
  return window['go']['main']['App']['ManifestExists'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function StartBackup(arg1) {
  return window['go']['main']['App']['StartBackup'](arg1);
}

export function TriggerTrustCheck(arg1) {
  return window['go']['main']['App']['TriggerTrustCheck'](arg1);
}
