// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';
import {device} from '../models';
import {platform} from '../models';

export function CancelBackup():Promise<void>;

export function CheckAppleDevicesInstalled():Promise<boolean>;

export function CheckBackupPath(arg1:string):Promise<void>;

export function CheckTrustStatus(arg1:string):Promise<boolean>;

export function EstimateBackupSize(arg1:string,arg2:string):Promise<number>;

export function GetAutostart():Promise<boolean>;

export function GetBackupEstimate(arg1:string,arg2:string):Promise<backup.BackupEstimate>;

export function GetBackupFolderSize(arg1:string):Promise<number>;

export function GetBackupHistory():Promise<Array<config.BackupRecord>>;

export function GetConnectedDevice():Promise<device.DeviceInfo>;

export function GetDefaultBackupPath():Promise<string>;

export function GetDeviceDetail(arg1:string):Promise<device.DeviceDetail>;

export function GetDiskInfo(arg1:string):Promise<platform.DiskInfo>;

export function GetPlatformInfo():Promise<platform.Info>;

export function InstallAppleDevices():Promise<void>;

export function InstallHeicCodec():Promise<void>;

export function LaunchAppleDevices():Promise<void>;

export function LoadConfig():Promise<config.AppConfig>;

export function ManifestExists(arg1:string,arg2:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SelectBackupFolder():Promise<string>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function StartBackup(arg1:backup.BackupConfig):Promise<void>;

export function TriggerTrustCheck(arg1:string):Promise<boolean>;
